#!/usr/bin/env bash

zip -r ${NODIS_ARTIFACT_NAME} . -x '*.git*'

aws s3 cp ${NODIS_ARTIFACT_NAME} s3://${NODIS_ARTIFACT_BUCKET}/${NODIS_ARTIFACT_PATH}/
aws s3 cp s3://${NODIS_ARTIFACT_BUCKET}/${NODIS_ARTIFACT_PATH}/${NODIS_ARTIFACT_NAME} s3://${NODIS_ARTIFACT_BUCKET}/${NODIS_ARTIFACT_PATH}/${NODIS_ARTIFACT_FULLNAME}